# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/0wax3z5fj5bg57qmrqalqvykikqs7yva-hm-session-vars.fish

set fish_greeting # Disable greeting
fish_vi_key_bindings

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations
    abbr --add -- cat 'bat --paging=never'
    abbr --add -- hs 'home-manager switch --flake ~/nix-config#xu@xuz13'
    abbr --add -- l 'ls -l'
    abbr --add -- lst 'eza --sort newest -l'
    abbr --add -- ns 'git add ~/nix-config && git commit -m '\''.'\'' && git push; sudo nixos-rebuild switch --flake ~/nix-config#xuz13'

    # Aliases
    alias eza 'eza --icons auto'
    alias la 'eza -a'
    alias ll 'eza -l'
    alias lla 'eza -la'
    alias ls eza
    alias lt 'eza --tree'
    # alias nmtui 'NEWT_COLORS="root=lavender,crust border=sapphire,base window=overlay0,base title=rosewater,crust button=surface2,lavender button_active=crust,maroon" nmtui'

    # Interactive shell initialisation
    /nix/store/z3ayhjslz72ldiwrv3mn5n7rs96p2g8a-fzf-0.62.0/bin/fzf --fish | source

    /nix/store/9f7y6h4yij2x0x6v35a7yjm5qyvvrjjs-zoxide-0.9.7/bin/zoxide init fish | source

    if test "$TERM" != dumb
        /nix/store/sa6y5dghbdj04i4dwz7lxglfk1iafdci-starship-1.23.0/bin/starship init fish | source

    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/xu/.local/share/fish/home-manager_generated_completions" $post
    end

end
